name: Build Test

on:
  [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt install gcc

    - name: Build
      run: make build
